version: '2'
services:
  web:
    image: "node:slim"
    command: node server.js
    environment:
      - NODE_ENV=development
    ports:
      - "4000:4000"
    volumes:
      - .:/app
    working_dir: /app
    depends_on:
      - db
  db:
    image: "neo4j"
    environment:
      - NEO4J_AUTH=none
    ports:
      - "7474:7474"
      - "7687:7687"
    volumes:
      - ./data:/data
