version: '3'
services:
  api:
    build: .
    command: nodemon --watch src src
    environment:
      - NODE_ENV=development
    ports:
      - "4000:80"
    volumes:
      - .:/app
    working_dir: /app
    depends_on:
      - db
  db:
    image: neo4j:3.2
    environment:
      - NEO4J_AUTH=none
      - EXTENSION_SCRIPT=/extensions/extension_script.sh
    ports:
      - "7474:7474"
      - "7687:7687"
    volumes:
      - ./data/extensions:/extensions
